# docker-compose build
# docker-compose up -d


FROM alpine
RUN mkdir /app
WORKDIR /app
COPY package.json /myapp/package.json

RUN npm install
COPY . /app/

# # # 暴露容器端口
EXPOSE 7001
# # # Start the application
CMD ["npm","run","start"]


