
version: '3'
services:
  web:
    build: .
    command: npm run start
    # restart: always
    deploy:
      replicas: 2
    volumes:
      - .:/myapp
    ports:
      - "7001:7001"



  mongo:
      container_name: mongo
      image: mongo
      restart: always
  redis:
      image: redis
volumes:
  db-data:
