# docker-compose build
# docker-compose up -d


FROM node:14-alpine
RUN mkdir /app
WORKDIR /app
COPY package.json /myapp/package.json

# RUN npm install
# RUN npm i --production --registry=https://registry.npm.taobao.org
RUN npm i --registry=https://registry.npm.taobao.org

# 安装额外的插件
RUN npm install egg-redis egg-mongoose
COPY . /app/

# # # 暴露容器端口
EXPOSE 7001
# # # Start the application
# CMD ["npm","run","start"]
CMD npm start


