version: '3.2'
services:


  egg-redis:
    image: 'redis'
    ports:
      - '6379:6379'


  web:
    restart: on-failure
    environment:
      EGG_SERVER_ENV: prod
      NODE_ENV: production
    build: ./
    deploy:
      replicas: 1
    hostname: web1
    ports:
      - "7001:7001"
    depends_on:
      - egg-mongoose
      - egg-redis


  egg-mongoose:
    container_name: egg-mongoose
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: momo
    ports:
      - "27017:27017"

