
version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
        - my-server



  redis:
    container_name: redis
    image: redis
    ports:
        - "6379:6379"
    restart: on-failure
    networks:
        - my-server


networks:
  my-server:
    # driver: bridge
