# 使用 Node.js 14 镜像作为基础镜像
FROM node:14

# 设置时区
RUN apk --update add tzdata \
  && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo "Asia/Shanghai" > /etc/timezone \
  && apk del tzdata


# 设置工作目录
WORKDIR /app



# 安装依赖
RUN npm install

# 将项目文件拷贝到工作目录
COPY . /app

# 暴露应用端口（根据你的 Egg.js 项目配置）
EXPOSE 7001

# 启动应用
CMD ["npm", "start"]
