# docker build -t my-egg-app .
# docker-compose up


# node镜像
FROM node:slim

# 这个是容器中的文件目录
RUN mkdir /myapp

# 设置工作目录
WORKDIR /myapp

# 拷贝package.json文件到工作目录
COPY package.json /myapp/package.json

# 安装npm依赖(使用淘宝的镜像源)
# 如果使用的境外服务器，无需使用淘宝的镜像源，即改为`RUN npm i`。
RUN npm i --registry=https://registry.npm.taobao.org

# 拷贝所有源代码到工作目
COPY . /myapp/

# # 暴露容器端口
# EXPOSE 7001

# # CMD [ "npm", "start" ]
# # 启动应用
# CMD ["npm", "run", "start"]


