# docker build -t my-egg-app .
# docker run -p 7001:7001  my-egg-app
# docker-compose build
# docker-compose up -d


FROM node:slim
RUN mkdir /myapp
WORKDIR /myapp
COPY package.json /myapp/package.json
RUN npm i --registry=https://registry.npm.taobao.org
COPY . /myapp/

# # 暴露容器端口
EXPOSE 7001


# # Start the application
# CMD ["npm","start"]
# CMD ["npm", "run"]
# CMD ["npm", "run", "start"]
CMD ["npm", "run", "dev"]
