# 使用 Node.js 14 镜像作为基础镜像
FROM node:14

# 设置时区
RUN apk --update add tzdata \
  && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo "Asia/Shanghai" > /etc/timezone \
  && apk del tzdata


# 设置工作目录
WORKDIR /app

# 拷贝package.json文件到工作目录
# !!重要：package.json需要单独添加。
# Docker在构建镜像的时候，是一层一层构建的，仅当这一层有变化时，重新构建对应的层。
# 如果package.json和源代码一起添加到镜像，则每次修改源码都需要重新安装npm模块，这样木有必要。
# 所以，正确的顺序是: 添加package.json；安装npm模块；添加源代码。
COPY package.json /app/package.json

# 安装依赖
RUN npm install

# 将项目文件拷贝到工作目录
COPY . /app

# 暴露应用端口（根据你的 Egg.js 项目配置）
EXPOSE 7001

# 启动应用
CMD ["npm", "start"]
