# docker-compose build
# docker-compose up -d


FROM alpine
RUN mkdir /myapp
WORKDIR /myapp
COPY package.json /myapp/package.json
# RUN apk add nodejs npm && npm i --registry=https://registry.npm.taobao.org && npm i && npm run tsc
RUN npm i --registry=https://registry.npm.taobao.org
COPY . /myapp/

# # # 暴露容器端口
# EXPOSE 7001
# # # Start the application
CMD ["npm","start"]


